### ISSUE TITLE
Playground

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/draft-iguide-bulkhead#8]
Playground to explore the @bulkhead, @Asynchronous, value and waitingTaskQueue parameter values.

**Comment by aknguyen7** [comment]
feedback from today playback:
1. playground do value=5, waitingTaskQueue=5. Add a note, if they change the value and the waiting queue is smaller, pop up a message to say the best practice is to have it the same size or larger
2. need more “WOW” in the playground?
