### ISSUE TITLE
Update the Best Practice statement

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/draft-iguide-bulkhead#95]
Within the guide, on the 'Adding the @Asynchronous annotation with @Bulkhead' and in the playground step we indicate that making the **waitingTaskQueue** parameter value greater than or equal to the **value** parameter is a best practice.   **Add more to explain why.**

From Tom Evans:
The javadoc for waitingTaskQueue says;
* Specify the waiting task queue. This setting only takes effect on asynchronous invocation, achieved by using {@code Asynchronous}.
* The value must be greater than 0.
* Otherwise, {@link org.eclipse.microprofile.faulttolerance.exceptions.FaultToleranceDefinitionException} occurs.

What that means is; if @Asynchronous is used then there is always a queue and the queue size must be greater than zero.

Best practice (not spec) is that the queue size is the same as the bulkhead and the default values (in the spec) reflect that (10 and 10).

**Comment by kinueng** [comment]
@mbroz2 
Do you know from recent conversations on what was the motivations for this best practice?

**Comment by kinueng** [comment]
We chatted about this during the backlog grooming and we are thinking about just putting a small reasoning that the best practice is to maintain "maximum efficiency"
